name: Continuous Integration with GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log in Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${DOCKER_PASSWORD}
          password: ${DOCKER_PASSWORD}
